name: Update Parent Issues on Comment

on:
  issue_comment:
    types: [created]

permissions:
  issues: write
  pull-requests: read
  contents: read

jobs:
  update-parent-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Authenticate with GitHub CLI
        run: gh auth login --with-token <<< ${{ secrets.GITHUB_TOKEN }}

      - name: Update Parent Issues
        run: |
          set -e

          ISSUE_NUMBER=${{ github.event.issue.number }}
          REPO=${{ github.repository }}

          # Fetch the issue body
          BODY=$(gh issue view $ISSUE_NUMBER --json body -q .body)

          # Extract the "Parents:" line from the body
          PARENTS_LINE=$(echo "$BODY" | grep -oP 'Parents:\s*#[0-9, ]+')

          if [ -z "$PARENTS_LINE" ]; then
            echo "No Parents found, exiting."
            exit 0
          fi

          # Extract parent issue numbers
          PARENT_IDS=$(echo "$PARENTS_LINE" | grep -oP '#\d+' | grep -oP '\d+')

          # Loop through each parent to update its description with child issues
          for PARENT_ID in $PARENT_IDS; do
            # Fetch the current description
            PARENT_DESCRIPTION=$(gh issue view $PARENT_ID --json body -q .body)

            # Remove existing "Children:" line if it exists
            UPDATED_DESCRIPTION=$(echo "$PARENT_DESCRIPTION" | sed '/^Children:/d')

            # Collect existing child issues
            EXISTING_CHILDREN=$(echo "$UPDATED_DESCRIPTION" | grep -oP 'Children:\s*#[0-9, ]*' | sed 's/Children:\s*//')

            # Construct the new children line
            CHILDREN_LINE="Children: $(echo "$EXISTING_CHILDREN #$ISSUE_NUMBER" | tr -s ' ' | sed 's/ #/\n#/g')"

            # Append the new "Children:" line at the beginning
            FINAL_DESCRIPTION="${CHILDREN_LINE}\n\n${UPDATED_DESCRIPTION}"

            # Update the parent issue with the new description
            gh issue edit $PARENT_ID --body "$FINAL_DESCRIPTION"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
